conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: ffhq
  root: ../input/celebahq/celeba_hq/val/male

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [128, 129]  # for box
    # mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256


  noise:
    name: poisson
    rate: 1
